# See http://about.travis-ci.org/docs/user/build-configuration/
branches:
  only:
    - master

language: scala
scala:
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk7

script:
  - sbt clean compile coverage test && sbt coverageAggregate

before_install:
  - pip install --user codecov

after_success:
  - codecov